DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS images;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  admin BOOL DEFAULT 0
);

CREATE TABLE images(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  image_data BLOB NOT NULL,
  model_label TEXT DEFAULT NULL,
  user_label TEXT DEFAULT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);